DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS options CASCADE;

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL
);


CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id  INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255)
);


CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id  INTEGER REFERENCES polls(id) ON DELETE CASCADE,
  option_id INTEGER REFERENCES options(id) ON DELETE CASCADE,
  rank INTEGER NOT NULL
);

